GET http://localhost:8080/api/v1/deployments?email=michael%40michaelpeterswa.com&provider=github HTTP/1.1
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..iriEeHi2B06LqWX_ood5ng.SOSFfUiDuk5yrgGhMK4bO84_PeY0BrDmxp0Jr-D1NwFLnT9Ps3LZ5v7X4y6w_Tp_ghZUwqwfgiy3iz10fiW66RRx3N_GF8JjeDYJ66vwhq5jZX09jn-tFHxViXU0s8kno-ZmfaVExKSUyRvS1ia9JCUZ6VxHSn_wVBZQXimoIGGwAj-PF3t7Irx6b0kobPyZAML6Telv2mYejH_oyO1BYgJonGj2e19ta7pRkN97-s9C2fMvFBOkeOOfk0g3g6nJxNqSClKr8jS9YdEIHfcdn8XvBbRmmJrLsD_fhGNQaQ4bNXO_Bere32ofj308YFRaLIjKgJjqWGvr43bwjMCqMhkZo50tQb29gxppW-UmD6c-I9cpJpYNlrpmEtCulXmNr3TIwUPGcQEbwJgP7RUTDw.7kZMAHdtdjB74w6B-XZ4jg
